<script>
    import Footer from "$lib/components/shared/Footer.svelte";
</script>
<svelte:head>
    <title>Terms & Conditions</title>
</svelte:head>
<header class="header bg-zinc-800 flex justify-between">
    <a href="javascript:history.back()" class="back-button flot bg-[#ccfc7e]">Back</a>
    <img src="./logo.png" class="logo-img" alt="Company Logo" />
</header>

<div class="main-container">
    <h1 class="flot-b" style="font-size: 27px;">Terms and Conditions</h1>

    <p class="border border-black rounded-md p-2 flot bg-black text-white" style="margin-top: 10px; margin-bottom: 10px;">Last updated: April 19, 2025</p>
  
    <p>Welcome to Metag. These Terms and Conditions ("Terms") govern your use of our website, application, and services ("Services"). By accessing or using Metag, you agree to be bound by these Terms.</p>
  
    <h2 class="flot">1. Acceptance of Terms</h2>
    <p>By accessing or using Metag, you confirm that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, please do not use our Services.</p>
  
    <h2 class="flot">2. Services Provided</h2>
    <p>Metag is an AI-powered tool designed to help users generate high-quality LinkedIn posts. Users input prompts and preferences, and Metag generates content based on those inputs using AI models.</p>
  
    <h2 class="flot">3. Eligibility</h2>
    <p>To use Metag, you must be at least 13 years old. By using our Services, you represent that you meet this age requirement and are fully able and competent to enter into these Terms.</p>
  
    <h2 class="flot">4. User Accounts</h2>
    <p>To access some features, you may be required to create an account. You are responsible for safeguarding your password and agree not to disclose your credentials to any third party.</p>
  
    <h2 class="flot">5. Acceptable Use</h2>
    <p>You agree not to use the Service for any unlawful purpose or in violation of any applicable law. You may not use Metag to generate or share content that is harmful, misleading, abusive, defamatory, or offensive.</p>
  
    <h2 class="flot">6. Intellectual Property</h2>
    <p>All content, branding, logos, and technology used in Metag are the property of Metag or its licensors. You may not copy, reproduce, or use our content without written permission, except for content you generated and downloaded.</p>
  
    <h2 class="flot">7. User-Generated Content</h2>
    <p>You retain rights to the content you generate using Metag. However, you grant Metag a non-exclusive, royalty-free license to use your content for service improvement and analytics unless you delete it or request removal.</p>
  
    <h2 class="flot">8. AI Content Disclaimer</h2>
    <p>AI-generated content may occasionally contain errors or inaccuracies. You are responsible for reviewing and editing content before publishing. Metag disclaims liability for content generated by the AI.</p>
  
    <h2 class="flot">9. Subscription and Billing</h2>
    <p>If you subscribe to a paid plan, you agree to pay all fees associated with the plan selected. Payments are processed securely through our third-party payment provider. All fees are non-refundable unless required by law.</p>
  
    <h2 class="flot">10. Termination</h2>
    <p>We may suspend or terminate your access to the Services at any time if you violate these Terms. You may also delete your account at any time via your dashboard.</p>
  
    <h2 class="flot">11. Limitation of Liability</h2>
    <p>Metag shall not be liable for any indirect, incidental, special, or consequential damages arising out of your use of or inability to use the Services. Our total liability shall not exceed the amount you paid us in the past 6 months.</p>
  
    <h2 class="flot">12. Modifications</h2>
    <p>We may update these Terms from time to time. If changes are material, we will notify you via email or through the platform. Continued use after the update constitutes acceptance of the new Terms.</p>
  
    <h2 class="flot">13. Privacy</h2>
    <p>Your privacy is important to us. Please review our <a href="/privacy-policy">Privacy Policy</a> for more information about how we collect, use, and protect your data.</p>
  
    <h2 class="flot">14. Governing Law</h2>
    <p>These Terms shall be governed by the laws of the jurisdiction in which Metag operates, without regard to conflict of law provisions.</p>
  
    <h2 class="flot">15. Contact Us</h2>
    <p>If you have any questions about these Terms, please contact us at <a href="mailto:support@metag.ai">support@metag.ai</a>.</p>
  
</div>
<Footer />
<style>
    .header {
        padding: 18px 24px;
        display: flex;
        align-items: center;
        gap: 20px;
        position: fixed;
        width: 100%;
        top: 0;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
    }

    .back-button {
        border-radius: 5px;
        display: flex;
        align-items: center;
        justify-content: center;
        text-decoration: none;
        font-size: 15px;
        transition: all 0.2s ease;
        padding: 5px;
    }

    .back-button:hover {
        background-color: #f8f9fa;
        transform: scale(1.05);
    }

    .logo-img {
        height: 32px;
        width: auto;
        object-fit: contain;
    }

    .main-container {
        max-width: 800px;
        margin: 100px auto 40px;
        padding: 40px;
        background: #ffffff;
        border-radius: 16px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    .content-heading {
        color: #1a1a1a;
        font-size: 32px;
        margin-bottom: 32px;
        padding-bottom: 16px;
        border-bottom: 2px solid #f0f0f0;
    }

    .section-heading {
        color: #2c3e50;
        font-size: 20px;
        margin: 24px 0 12px;
    }

    .section-text {
        color: #666666;
        font-size: 15px;
        line-height: 1.7;
        margin-bottom: 20px;
    }
</style>
